package recipe.app.rest.model;
// default package

// Generated Apr 16, 2020 3:33:16 PM by Hibernate Tools 5.4.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * AppUser generated by hbm2java
 */
@Entity
@Table(name = "app_user", schema = "my_recipes")
public class AppUser implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1179684729236839897L;
	private Integer appUserId;
	private String userName;
	private String firstName;
	private String lastName;
	private String emailAddress;
	private String country;
	private byte[] profilePic;
	private String password;
	Set<Recipe> recipes = new HashSet<Recipe>(0);

	public AppUser() {
	}

	public AppUser(Integer appUserId, String userName, String firstName, String emailAddress) {
		this.appUserId = appUserId;
		this.userName = userName;
		this.firstName = firstName;
		this.emailAddress = emailAddress;
	}

	public AppUser(Integer appUserId, String userName, String firstName, String lastName, String emailAddress,
			String country, byte[] profilePic, String password, Set<Recipe> recipes) {
		this.appUserId = appUserId;
		this.userName = userName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailAddress = emailAddress;
		this.country = country;
		this.profilePic = profilePic;
		this.password = password;
		this.recipes = recipes;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "appUserSeq")
	@SequenceGenerator(name = "appUserSeq", sequenceName = "app_user_app_user_id_seq", allocationSize = 1)
	@Column(name = "app_user_id", unique = true, nullable = false)
	public Integer getAppUserId() {
		return this.appUserId;
	}

	public void setAppUserId(Integer appUserId) {
		this.appUserId = appUserId;
	}

	@Column(name = "user_name", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "first_name", nullable = false, length = 20)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 20)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email_address", nullable = false, length = 50)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "country", length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "profile_pic")
	public byte[] getProfilePic() {
		return this.profilePic;
	}

	public void setProfilePic(byte[] profilePic) {
		this.profilePic = profilePic;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appUser")
	public Set<Recipe> getRecipes () {
		return this.recipes;
	}
	
	public void setRecipes(Set<Recipe> recipes) {
		this.recipes = recipes;
	}

}
