package recipe.app.rest.model;
// default package

// Generated Apr 16, 2020 3:33:16 PM by Hibernate Tools 5.4.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", schema = "my_recipes")
public class Category implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 5455857858153907751L;
	private Integer categoryId;
	private String categoryName;
	private String categoryDescription;
	private Set<RecipeCategory> recipeCategories = new HashSet<RecipeCategory>(0);

	public Category() {
	}

	public Category(Integer categoryId, String categoryName, String categoryDescription) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.categoryDescription = categoryDescription;
	}

	public Category(Integer categoryId, String categoryName, String categoryDescription,
			Set<RecipeCategory> recipeCategories) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.categoryDescription = categoryDescription;
		this.recipeCategories = recipeCategories;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "categorySeq")
	@SequenceGenerator(name = "categorySeq", sequenceName = "category_category_id_seq", allocationSize = 1)
	@Column(name = "category_id", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "category_name", nullable = false)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "category_description", nullable = false)
	public String getCategoryDescription() {
		return this.categoryDescription;
	}

	public void setCategoryDescription(String categoryDescription) {
		this.categoryDescription = categoryDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<RecipeCategory> getRecipeCategories() {
		return this.recipeCategories;
	}

	public void setRecipeCategories(Set<RecipeCategory> recipeCategories) {
		this.recipeCategories = recipeCategories;
	}

}
