package recipe.app.rest.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import recipe.app.rest.model.AppUser;
import recipe.app.rest.repository.AppUserRepository;

/**
* Generated by Spring Data Generator on 16/04/2020
*/
@Component
public class AppUserServiceImpl {

	private AppUserRepository appUserRepository;

	@Autowired
	public AppUserServiceImpl(AppUserRepository appUserRepository) {
		this.appUserRepository = appUserRepository;
	}

}
