package recipe.app.rest.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import recipe.app.rest.model.Category;
import recipe.app.rest.repository.CategoryRepository;

/**
* Generated by Spring Data Generator on 16/04/2020
*/
@Component
public class CategoryServiceImpl {

	private CategoryRepository categoryRepository;

	@Autowired
	public CategoryServiceImpl(CategoryRepository categoryRepository) {
		this.categoryRepository = categoryRepository;
	}

}
