package recipe.app.rest.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import recipe.app.rest.model.Recipe;
import recipe.app.rest.repository.RecipeRepository;

/**
* Generated by Spring Data Generator on 16/04/2020
*/
@Component
public class RecipeServiceImpl implements RecipeService {

	private RecipeRepository recipeRepository;

	@Autowired
	public RecipeServiceImpl(RecipeRepository recipeRepository) {
		this.recipeRepository = recipeRepository;
	}
	
	public Recipe saveRecipe(Recipe recipeData) {
		return recipeRepository.save(recipeData);
	}

}
