package recipe.app.rest.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.web.bind.annotation.CrossOrigin;

import recipe.app.rest.model.AppUser;

/**
* Generated by Spring Data Generator on 16/04/2020
*/
@RepositoryRestResource(path = "appUser")
@CrossOrigin
public interface AppUserRepository extends CrudRepository<AppUser, Integer>{
	AppUser findByUserName(@Param("userName") String userName);
}
