package recipe.app.rest.repository;


import org.springframework.data.repository.CrudRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.web.bind.annotation.CrossOrigin;

import recipe.app.rest.model.Category;

/**
* Generated by Spring Data Generator on 16/04/2020
*/
@RepositoryRestResource(path = "category")
@CrossOrigin
public interface CategoryRepository extends CrudRepository<Category, Integer>{

}
