package recipe.app.rest.repository;


import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.CrossOrigin;

import recipe.app.rest.model.Recipe;

/**
* Generated by Spring Data Generator on 16/04/2020
*/
@RepositoryRestResource(path = "recipe")
@CrossOrigin
public interface RecipeRepository extends CrudRepository<Recipe, Integer> {
	
	Recipe findByRecipeName(@Param("recipeName") String recipeName);
}
